customer_name: "Amelie's Street Bar"
kvkk_link: "https://drive.google.com/file/d/1oopjlo1PBvCSbtnzQg24GuUgotvb0eUm/view?usp=sharing/"
logo_path: "./assets/images/logo.png"
footer_message: "🔄 Sorun olursa üst köşedeki ↻ ile ekranı yenileyin!"


